### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by happytm** [pouriamoosavi/LittleDB#2] opened 2021-05-05 22:49 UTC
While trying to compile your code I get following compile error:

Compiling library "LittleDB"
"C:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H -DGCC_NOT_5_2_0=0 -DWITH_POSIX "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/config" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/app_trace" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/app_update" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/asio" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/bootloader_support" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/bt" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/coap" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/console" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/driver" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp-tls" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp32" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_adc_cal" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_event" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_http_client" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_http_server" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_https_ota" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_ringbuf" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/ethernet" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/expat" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/fatfs" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/freemodbus" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/freertos" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/heap" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/idf_test" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/jsmn" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/json" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/libsodium" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/log" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/lwip" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/mbedtls" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/mdns" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/micro-ecc" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/mqtt" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/newlib" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/nghttp" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/nvs_flash" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/openssl" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/protobuf-c" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/protocomm" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/pthread" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/sdmmc" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/smartconfig_ack" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/soc" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/spi_flash" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/spiffs" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/tcp_transport" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/tcpip_adapter" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/ulp" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/vfs" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/wear_levelling" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/wifi_provisioning" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/wpa_supplicant" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/xtensa-debug-module" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp-face" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp32-camera" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp-face" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/fb_gfx" -std=gnu++11 -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -Wall -Werror=all -Wextra -Wno-error=maybe-uninitialized -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-missing-field-initializers -Wno-sign-compare -fno-rtti -MMD -c -DF_CPU=240000000L -DARDUINO=10809 -DARDUINO_LOLIN32 -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"LOLIN32\"" "-DARDUINO_VARIANT=\"lolin32\"" -DESP32 -DCORE_DEBUG_LEVEL=0 "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4\\cores\\esp32" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4\\variants\\lolin32" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4\\libraries\\FS\\src" "-IC:\\Users\\WinCycle\\Documents\\Arduino\\libraries\\LittleFS_esp32\\src" "-IC:\\Users\\WinCycle\\Documents\\Arduino\\libraries\\LittleDB" "C:\\Users\\WinCycle\\Documents\\Arduino\\libraries\\LittleDB\\LittleDB.cpp" -o "C:\\Users\\WinCycle\\AppData\\Local\\Temp\\arduino_build_451345\\libraries\\LittleDB\\LittleDB.cpp.o"
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp: In function 'void listDir(fs::FS&, String, uint8_t)':

C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp:13:53: error: format '%s' expects argument of type 'char*', but argument 3 has type 'String*' [-Werror=format=]

   Serial.printf("Listing directory: %s\r\n", dirname);

                                                     ^

cc1plus.exe: some warnings being treated as errors

Using library FS at version 1.0 in folder: C:\Users\WinCycle\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\FS 
Using library LittleFS_esp32 at version 1.0.6 in folder: C:\Users\WinCycle\Documents\Arduino\libraries\LittleFS_esp32 
Using library LittleDB in folder: C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB (legacy)
exit status 1
Error compiling for board WEMOS LOLIN32.

**Comment by happytm** [comment] 2021-05-05 23:33
By commenting out line 13 in LittleDB.cpp file I was able to compile it fine. Now how your library can be used in practicle manner?

I have a home automation project where I will get sensor data from about 25 remote devices every few minutes. Each remote device will send about 10 types of sensor readings or device status in integer values and I want to log this data in a master table with your library.  Eventually I want to display this data on a webpage via ESP32 webserver.

Is this possible ? If so can you help me figure it out ?
Thanks.

**Comment by pouriamoosavi** [comment] 2021-05-06 05:44
Hi
Thank you for show me the problem and the solution, It seems that line was extra and can be omitted.

About your seconds question, as long as your data types are integer (in the range -2,147,483,647 - 2,147,483,647) or Strings (With no limit in length) you can store your data with this library. 
Although there are some problems if you have a lot of data with lots of rows. For example there is no indexing system, so reading from a long table could take some time.
There is a test folder with a `test_esp32DB` file in it with you can refer for some samples. In general it isn't that complicated:
- Create a database
- Connect to it
- Create table (with it's schema)
- Insert and select from table

If you need more help and/or find more errors please don't hesitate to reply again.
Thanks.

**Comment by happytm** [comment] 2021-05-06 05:51
Thank you for your reply.I will be testing it in next few days.

**Comment by happytm** [comment] 2021-05-06 08:23
I created a test file linked below :

https://github.com/happytm/LittleDB/blob/master/test/sensors.ino

When I try to select and print data it has some mysterious lines are added to location field.  I checked all my serial statements but there is nothing printing it from sketch.The lines are as follows:

 "insert into test_tbl values (1".
 "insert into test_tbl values (2".
 "insert into test_tbl values (3".
 "insert into test_tbl values (4".

What could be the problem ?

Thanks.

**Comment by happytm** [comment] 2021-05-06 18:58
My above problem is solved. I had a white space when building a insert statement. Code updated at following link:

https://github.com/happytm/LittleDB/blob/master/test/sensors.ino

Now if you can make other fields besides id field  work for select statement it would be very useful to get data back from table specially the date and location field in my sketch.

Thanks.

**Comment by pouriamoosavi** [comment] 2021-05-07 05:17
Glad that your problem has been solved.
I think I can work on `select` this weekend but it may take a while. I'll let you know.

**Comment by happytm** [comment] 2021-05-07 06:51
Thanks.

**Comment by happytm** [comment] 2021-05-07 22:48
Thank you for library update. 

Unfortunately, I have compile error again for Arduino shown below:

```Compiling library "LittleDB"
"C:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H -DGCC_NOT_5_2_0=0 -DWITH_POSIX "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/config" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/app_trace" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/app_update" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/asio" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/bootloader_support" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/bt" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/coap" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/console" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/driver" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp-tls" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp32" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_adc_cal" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_event" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_http_client" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_http_server" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_https_ota" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp_ringbuf" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/ethernet" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/expat" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/fatfs" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/freemodbus" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/freertos" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/heap" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/idf_test" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/jsmn" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/json" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/libsodium" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/log" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/lwip" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/mbedtls" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/mdns" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/micro-ecc" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/mqtt" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/newlib" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/nghttp" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/nvs_flash" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/openssl" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/protobuf-c" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/protocomm" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/pthread" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/sdmmc" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/smartconfig_ack" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/soc" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/spi_flash" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/spiffs" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/tcp_transport" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/tcpip_adapter" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/ulp" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/vfs" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/wear_levelling" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/wifi_provisioning" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/wpa_supplicant" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/xtensa-debug-module" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp-face" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp32-camera" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/esp-face" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4/tools/sdk/include/fb_gfx" -std=gnu++11 -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -Wall -Werror=all -Wextra -Wno-error=maybe-uninitialized -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-missing-field-initializers -Wno-sign-compare -fno-rtti -MMD -c -DF_CPU=240000000L -DARDUINO=10813 -DARDUINO_LOLIN32 -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"LOLIN32\"" "-DARDUINO_VARIANT=\"lolin32\"" -DESP32 -DCORE_DEBUG_LEVEL=0 "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4\\cores\\esp32" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4\\variants\\lolin32" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4\\libraries\\WiFi\\src" "-IC:\\Users\\WinCycle\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.4\\libraries\\FS\\src" "-IC:\\Users\\WinCycle\\Documents\\Arduino\\libraries\\LittleFS_esp32\\src" "-IC:\\Users\\WinCycle\\Documents\\Arduino\\libraries\\LittleDB" "-IC:\\Users\\WinCycle\\Documents\\Arduino\\libraries\\ESPDateTime\\src" "C:\\Users\\WinCycle\\Documents\\Arduino\\libraries\\LittleDB\\LittleDB.cpp" -o "C:\\Users\\WinCycle\\AppData\\Local\\Temp\\arduino_build_881867\\libraries\\LittleDB\\LittleDB.cpp.o"
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp: In function 'bool valEqualRead(fs::File, String, String)':
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp:327:28: error: narrowing conversion of 'valInt' from 'int8_t {aka signed char}' to 'byte {aka unsigned char}' inside { } [-Werror=narrowing]
     byte valArr[] = {valInt};
                            ^
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp: In function 'int8_t execSelect(String)':
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp:811:36: error: 'SELECT_LEN' was not declared in this scope
   String tblName = query.substring(SELECT_LEN, whereIndex);
                                    ^
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp: In function 'int8_t execDelete(String)':
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp:903:36: error: 'DELETE_LEN' was not declared in this scope
   String tblName = query.substring(DELETE_LEN, whereIndex);
                                    ^
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp: In function 'int8_t execInsert(String)':
C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB\LittleDB.cpp:924:36: error: 'INSERT_LEN' was not declared in this scope
   String tblName = query.substring(INSERT_LEN, valuesIndex);
                                    ^
cc1plus.exe: some warnings being treated as errors
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\WinCycle\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
 Not used: C:\Arduino_1.8.12\portable\arduino-nightly\libraries\WiFi
Using library WiFi at version 1.0 in folder: C:\Users\WinCycle\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi 
Using library FS at version 1.0 in folder: C:\Users\WinCycle\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\FS 
Using library LittleFS_esp32 at version 1.0.6 in folder: C:\Users\WinCycle\Documents\Arduino\libraries\LittleFS_esp32 
Using library LittleDB in folder: C:\Users\WinCycle\Documents\Arduino\libraries\LittleDB (legacy)
Using library ESPDateTime at version 0.2.0 in folder: C:\Users\WinCycle\Documents\Arduino\libraries\ESPDateTime 
exit status 1
Error compiling for board WEMOS LOLIN32.

**Comment by pouriamoosavi** [comment] 2021-05-08 05:10
Changes are still in stage. I haven't test them myself yet. 
Please wait until I test them and merge them to master.

**Comment by happytm** [comment] 2021-05-08 06:06
Thank you I will wait.

**Comment by pouriamoosavi** [comment] 2021-05-08 13:28
Hi, hope you are well.
I think it is ready now! Please pull `stage` branch and test it, I will merge it with master soon.
You can refer to `test` directory to see select by other fields examples.
I've read your above error too and I think the problem is that you didn't include new `LittleDB.h` file. You should update it as it has some changes. 
Please let me know if there are any other problems.

**Comment by pouriamoosavi** [comment] 2021-05-08 13:29
By the way I fixed the `error: format '%s' expects argument of type 'char*', but argument 3 has type 'String*' [-Werror=format=]` error too. As it was always OK in my own system it would be great if you can test it and let me know if it is fixed or not.

**Comment by happytm** [comment] 2021-05-08 19:57
Beautiful! Now I can do so many things with your library. I was looking for a small SQL type database for ESP32 without good success. Your library is so simple to understand and it does it's work.

Thank you so much.

**Comment by pouriamoosavi** [comment] 2021-05-08 20:04
Glad you like it. Just pay attention that it only returns one row for every `select`. I will try to address this issue. But for now it is limited to one row. 
I'll close this issue if it's ok.

**Closed as completed by pouriamoosavi** 2021-05-08 20:04 UTC

**Comment by happytm** [comment] 2021-05-08 20:22
It's ok to close.

Thanks
